# package load

In [1]:
import numpy as np
import pandas as pd

# 로또 번호 자동 생성 함수 만들기

# np review

In [34]:
n=np.array([11,2,3,4])
print(n)
print(n.shape)
print(len(n))
print(n.T)
print(n[n!=11])

[11  2  3  4]
(4,)
4
[11  2  3  4]
[2 3 4]


In [15]:
# 1~45까지 랜덤으로 6개
import random

def lotto1():
    a=np.arange(1,46)
    x=np.random.choice(a,size=(1,1,6),replace=False)
    return x

print("이번 로또 번호는",lotto1())


TypeError: array() missing required argument 'object' (pos 1)

# titanic 데이터 이용하기

In [3]:
df=pd.read_csv("C:/Users/19178/TIL/AI_study/data/titanic.csv")

In [4]:
df.head()


pclass  survived                             name     sex      age  sibsp  \
0    1st         1    Allen, Miss. Elisabeth Walton  female  29.0000      0   
1    1st         1   Allison, Master. Hudson Trevor    male   0.9167      1   
2    1st         0     Allison, Miss. Helen Loraine  female   2.0000      1   
3    1st         0  Allison, Mr. Hudson Joshua Crei    male  30.0000      1   
4    1st         0  Allison, Mrs. Hudson J C (Bessi  female  25.0000      1   

   parch  ticket        fare    cabin     embarked  
0      0   24160  211.337494       B5  Southampton  
1      2  113781  151.550003  C22 C26  Southampton  
2      2  113781  151.550003  C22 C26  Southampton  
3      2  113781  151.550003  C22 C26  Southampton  
4      2  113781  151.550003  C22 C26  Southampton

In [5]:
print(df.describe())
print(df.shape)

          survived          age        sibsp        parch         fare
count  1309.000000  1046.000000  1309.000000  1309.000000  1308.000000
mean      0.381971    29.881135     0.498854     0.385027    33.295479
std       0.486055    14.413500     1.041658     0.865560    51.758669
min       0.000000     0.166700     0.000000     0.000000     0.000000
25%       0.000000    21.000000     0.000000     0.000000     7.895800
50%       0.000000    28.000000     0.000000     0.000000    14.454200
75%       1.000000    39.000000     1.000000     0.000000    31.275000
max       1.000000    80.000000     8.000000     9.000000   512.329224
(1309, 11)


In [37]:
df.dtypes
print(df['pclass'])
print(type(df['pclass']))
print(df.head)
print(df.head())


0       1st
1       1st
2       1st
3       1st
4       1st
       ... 
1304    3rd
1305    3rd
1306    3rd
1307    3rd
1308    3rd
Name: pclass, Length: 1309, dtype: object
<class 'pandas.core.series.Series'>
<bound method NDFrame.head of      pclass  survived                             name     sex      age  \
0       1st         1    Allen, Miss. Elisabeth Walton  female  29.0000   
1       1st         1   Allison, Master. Hudson Trevor    male   0.9167   
2       1st         0     Allison, Miss. Helen Loraine  female   2.0000   
3       1st         0  Allison, Mr. Hudson Joshua Crei    male  30.0000   
4       1st         0  Allison, Mrs. Hudson J C (Bessi  female  25.0000   
...     ...       ...                              ...     ...      ...   
1304    3rd         0             Zabour, Miss. Hileni  female  14.5000   
1305    3rd         0            Zabour, Miss. Thamine  female      NaN   
1306    3rd         0        Zakarian, Mr. Mapriededer    male  26.5000   
1307    3r

In [50]:
# df[df['age']>=30]
# df.loc[df['age']>=30,:]
print(df["pclass"])
print(df.pclass)
print(type(df.pclass))
n=np.array(df.pclass)
print(n)
print(n.shape)

df[(df['age']>=30) & (df['age'] < 40) & (df['pclass']== "2nd")].head()
df.info()

0       1st
1       1st
2       1st
3       1st
4       1st
       ... 
1304    3rd
1305    3rd
1306    3rd
1307    3rd
1308    3rd
Name: pclass, Length: 1309, dtype: object
0       1st
1       1st
2       1st
3       1st
4       1st
       ... 
1304    3rd
1305    3rd
1306    3rd
1307    3rd
1308    3rd
Name: pclass, Length: 1309, dtype: object
<class 'pandas.core.series.Series'>
['1st' '1st' '1st' ... '3rd' '3rd' '3rd']
(1309,)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    1309 non-null   object 
 1   survived  1309 non-null   int64  
 2   name      1309 non-null   object 
 3   sex       1309 non-null   object 
 4   age       1046 non-null   float64
 5   sibsp     1309 non-null   int64  
 6   parch     1309 non-null   int64  
 7   ticket    1309 non-null   object 
 8   fare      1308 non-null   float64
 9   cabin     295 non-null   

In [8]:
print(set(df['pclass']))
for i in set(df['pclass']):
    print(df.loc[df['pclass']== "{0}".format(i), 'age'].mean)

{'1st', '3rd', '2nd'}
<bound method Series.mean of 0      29.0000
1       0.9167
2       2.0000
3      30.0000
4      25.0000
        ...   
318        NaN
319    31.0000
320        NaN
321    62.0000
322    36.0000
Name: age, Length: 323, dtype: float64>
<bound method Series.mean of 600     42.0
601     13.0
602     16.0
603     35.0
604     16.0
        ... 
1304    14.5
1305     NaN
1306    26.5
1307    27.0
1308    29.0
Name: age, Length: 709, dtype: float64>
<bound method Series.mean of 323    30.0
324    28.0
325    30.0
326    18.0
327    25.0
       ... 
595     NaN
596    31.0
597     NaN
598    26.0
599    24.0
Name: age, Length: 277, dtype: float64>


In [11]:
l=list(set(df['pclass']))
l.sort()
for i in l:
    print("%s"%i, df.loc[df['pclass']== "%s"%i,'survived'].describe()['mean'])

for i in set(df['sex']):
    print("%s"%i, df.loc[df['sex']== "%s"%i,'survived'].describe()['mean'])


1st 0.6191950464396285
2nd 0.4296028880866426
3rd 0.2552891396332863
female 0.7274678111587983
male 0.19098457888493475
