# 3-1 Numpy

1.3 Numpy import

In [1]:
import numpy as np

2.1 리스트를 사용하여 numpy array 만들기

In [2]:
list1 = [7, 2, 9, 10]
print(list1)
print(type(list1))

[7, 2, 9, 10]
<class 'list'>


In [3]:
array1 = np.array(list1)
print(array1)
print(type(array1))

[ 7  2  9 10]
<class 'numpy.ndarray'>


In [4]:
list2 = [[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
print(list2)
print(type(list2))

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
<class 'list'>


In [5]:
array2 = np.array(list2)
print(array2)
print(type(array2))

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
<class 'numpy.ndarray'>


list.shape

In [6]:
array1.shape

(4,)

In [7]:
array2.shape

(2, 3)

In [8]:
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [9]:
b = np.array([1,2,3,4])
print(b)
print(type(b))
print(b.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [10]:
a = np.array([[1,2,3,4]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3 4]]
<class 'numpy.ndarray'>
(1, 4)


# Transpose
np.transpose()
.T

In [11]:
a = np.array([[1,2,3,4]])
print(a)
print(a.T)
print(np.transpose(a))

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]


In [12]:
print(b)
print(b.T)

[1 2 3 4]
[1 2 3 4]


In [13]:
array3 = np.array([[[0,1],[2,3],[4,5]],
                  [[6,7],[8,9],[10,11]],
                  [[12,13],[14,15],[16,17]],
                  [[18,19],[20,21],[22,23]]])
print(array3)
print(array3.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)


In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a=np.arange(1,10,2)
a.shape

(5,)

# reshape

In [17]:
a = np.arange(1,11)
a.shape

(10,)

In [18]:
b=a.reshape(2,5)
b.shape
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
c=a.reshape(5,2)
print(c)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [20]:
d = c.reshape(10,)
print(d)
print(d.shape)
a==d

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# np.ravel
,np.reshape의 반대 기능 => 1차원 array로 만들어주기
order = 'C' row 우선 변경(기본값)
order = 'F' column 우선 변경

In [21]:
a = np.arange(1,11)
b = a.reshape(2,5)
print(a)
print(b)
print(np.ravel(b))
print(np.ravel(b,order='F'))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  6  2  7  3  8  4  9  5 10]


In [22]:
a = np.arange(1,13)
b = a.reshape(2,2,3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
print(np.ravel(b,order='F'))
print(np.ravel(b,order='c'))

[ 1  7  4 10  2  8  5 11  3  9  6 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 2.3 numpy에서 제공하는 함수를 사용하여 numpy array 만들기
numpy에서 제공하는 함수를 사용하여 numpy array를 만들 수 있음
이러한 기능을 제공하는 함수로는 zeros(), ones(), full(), eye() 등이 있음
zeros() : 모든 값이 0인 array 생성
ones() : 모든 값이 1인 array 생성
full() : 사용자가 지정한 특정 값을 모든 값으로 하는 array 생성
eye() : 대각선으로는 1이고 나머지는 0인 2차원 array 생성(단위 행렬이라고 함)
numpy array의 값을 모두 0으로 대체하고 싶을 때는 zeros_like() 함수를 사용함


In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
x=np.array([[2,3,4],[6,5,4]])
print(x)

[[2 3 4]
 [6 5 4]]


In [29]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

# random 서브모듈 함수rand 함수를 통해 난수 생성
 
## np.random.rand(2,2,3)
0,1 사이의 균일 분포에서 난수 matrix array 생성

## np.random.randn(3,3,3)
평균0, 분산1의 표준정규분포 난수 matrix array 생성


In [30]:
np.random.rand(2,2,3)

array([[[0.73893968, 0.90376065, 0.57376362],
        [0.90737612, 0.59032531, 0.08346601]],

       [[0.58730153, 0.64075604, 0.91695763],
        [0.7591485 , 0.39085431, 0.41428595]]])

In [31]:
np.random.randn(3,3,3)

array([[[-0.58078773,  0.55419946, -0.48744048],
        [-0.44972623, -0.99548748, -0.51402847],
        [-1.03550337, -1.42030053,  0.76208631]],

       [[ 0.7089444 ,  0.58832685,  0.20970195],
        [-1.74387457, -0.05385776,  0.15986081],
        [ 0.06916944, -1.20038203,  1.36770508]],

       [[-0.65908126, -2.28605652,  1.91870195],
        [ 0.26959597,  1.61016402,  0.33380014],
        [ 0.62824057, -0.74435869, -0.43398694]]])

# seed 

## np.random.seed(2020)
## np.random.randn(3,3,3)

랜덤한 값 동일하게 다시 생성할 때 사용

In [32]:
np.random.seed(2020)
np.random.randn(3,3,3)

array([[[-1.76884571,  0.07555227, -1.1306297 ],
        [-0.65143017, -0.89311563, -1.27410098],
        [-0.06115443,  0.06451384,  0.41011295]],

       [[-0.57288249, -0.80133362,  1.31203519],
        [ 1.27469887, -1.2143576 ,  0.31371941],
        [-1.44482142, -0.3689613 , -0.76922658]],

       [[ 0.3926161 ,  0.05729383,  2.08997884],
        [ 0.04197131, -0.04834072, -0.51315392],
        [-0.08458928, -1.21545008, -1.41293073]]])

In [33]:
np.random.randn(3,3,3) #다름

array([[[-1.48691055,  0.38222486,  0.937673  ],
        [ 1.77267804,  0.87882801,  0.33171912],
        [-0.30603567,  1.24026615, -0.21562684]],

       [[ 0.15592948,  0.09805553,  0.83209585],
        [ 2.04520542, -0.31681392, -1.31283291],
        [-1.75445746,  0.10209408, -1.36150208]],

       [[ 0.48178488, -0.20832874, -0.09186351],
        [ 0.70268816,  0.10365506,  0.62123638],
        [ 0.95411497,  2.03781352, -0.48445122]]])

In [34]:
np.random.seed(2020) 
np.random.randn(3,3,3)

array([[[-1.76884571,  0.07555227, -1.1306297 ],
        [-0.65143017, -0.89311563, -1.27410098],
        [-0.06115443,  0.06451384,  0.41011295]],

       [[-0.57288249, -0.80133362,  1.31203519],
        [ 1.27469887, -1.2143576 ,  0.31371941],
        [-1.44482142, -0.3689613 , -0.76922658]],

       [[ 0.3926161 ,  0.05729383,  2.08997884],
        [ 0.04197131, -0.04834072, -0.51315392],
        [-0.08458928, -1.21545008, -1.41293073]]])

# choice 함수(랜덤 샘플링)

## np.random.choice(array, size=(), replace= T/F)

### replace = True 복원추출(기본값)
### replace = False 비복원추출

In [35]:
x=np.arange(1,50)
np.random.choice(x, size=(2,3,3), replace=False)
np.random.choice(x, size=(2,3,3), replace=True) #중복된 원소 가능

array([[[37, 14,  7],
        [45, 48, 31],
        [10, 14, 22]],

       [[14, 19, 15],
        [11, 28, 21],
        [36, 33, 10]]])

# 슬라이싱
1. 각 차원별 범위 지정
2. 차원의 수만큼 범위를 지정해줘야함
3. ex) 3차원이면 범위지정 총 3개
4. shape 의 element 개수가 차원의 수

In [36]:
x=np.arange(3,15)
y= x.reshape(3,2,2)
print(y)
y[:2,:,0]

[[[ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[3, 5],
       [7, 9]])

# 3.2 인덱싱


# 정수 인덱싱

### a[[row1, row2], [col1, col2]] => a[row1, col1] 과 a[row2, col2] 
### 입력                                               출력    

1. array 요소의 인덱스들을 일렬로 나열하여 부분집합을 구하는 방식임
    (범위지정 불가능)

2. 즉, 임의의 numpy array a에 대해 a[[row1, row2], [col1, col2]] 와 같이 표현하는 것인데, 이는 a[row1, col1] 과 a[row2, col2] 라는 두 개의 array 요소의 집합을 의미함



In [37]:
lst = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
a = np.array(lst)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
s = a[[0,1,2],[1,2,3]]
s

array([ 2,  7, 12])

# 부울린 인덱싱

## a[bool_indexing_array]

### bool_indexing = (a % 2 == 0)

In [39]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

 
bool_indexing_array = np.array([[False,  True, False],
                                [True,  False,  True],
                                [False,  True, False]])

 
a[bool_indexing_array]

array([2, 4, 6, 8])

4. 부울린 인덱싱 array에 True/False 값을 일일이 지정하는 방법 이외에 표현식을 사용하여 부울린 인덱싱 array를 생성하는 방법이 있음

ex) bool_indexing = (a % 2 == 0) 와 같이 표현할 수 있음

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b=a[a%2==0]
b.reshape(2,2)

array([[2, 4],
       [6, 8]])

## 다중조건 사용하기 ( & ,| )

### a[(a%2==0) & (a > 8)]

In [42]:
a=np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [43]:
a.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [44]:
a[(a%2==0) & (a > 8)]

array([10, 12, 14, 16])

In [45]:
a[(a%2==0) | (a % 3==0)]

array([ 2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16])

# 4. 연산

## 4-1 기본연산

### np.add(), np.subtract(), np.multiply(), np.divide()

In [46]:
a= np.array([1,2,3])
b= np.array([2,2,9])
print(a+b)
np.add(a,b)

[ 3  4 12]


array([ 3,  4, 12])

In [47]:
a-b

array([-1,  0, -6])

In [48]:
np.subtract(a,b)

array([-1,  0, -6])

In [49]:
a*b

array([ 2,  4, 27])

In [50]:
np.multiply(a,b)

array([ 2,  4, 27])

In [51]:
print(a / b)
print(np.divide(a, b))

[0.5        1.         0.33333333]
[0.5        1.         0.33333333]


## 4.2 행렬 곱 연산
### np.dot()

1. numpy에서 matrix의 product를 구하기 위해서 dot() 함수를 사용함
2. 아래 예제는 두 matrix의 product를 구한 예시

In [52]:
a=np.arange(1,5)
a= a.reshape(2,2)
a

b=np.arange(2,6)
b= b.reshape(2,2)
b

c= np.dot(a,b)
c

array([[10, 13],
       [22, 29]])

## 4.3 기준이 있는 연산

### np.sum() , np.prod(), np.mean()

###  (axis=0 : 열방향, axis=1: 행방향)

In [53]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
print(np.sum(a,axis=0))
np.sum(a,axis=1)

[12 15 18]


array([ 6, 15, 24])

In [55]:
np.prod(a,axis=0)

array([ 28,  80, 162])

In [56]:
np.prod(a)

362880

In [57]:
a.prod(axis=1)

array([  6, 120, 504])

In [58]:
a.mean()

5.0

##  4.4 array에 nan이 있을 때 연산

### nansum() : nan을 제외하고 연산

In [59]:
a= np.array([[1,2],[2,np.nan]])
a

array([[ 1.,  2.],
       [ 2., nan]])

In [60]:
a.sum()


nan

In [61]:
print(np.nansum(a))

5.0


## 5.기타함수 where()

### where(조건, 만족할 때의 출력 값, 만족하지 않을 때의 출력 값)

In [62]:
import numpy as np
np.random.seed(0)
a = np.random.randn(2,3,2)
a

array([[[ 1.76405235,  0.40015721],
        [ 0.97873798,  2.2408932 ],
        [ 1.86755799, -0.97727788]],

       [[ 0.95008842, -0.15135721],
        [-0.10321885,  0.4105985 ],
        [ 0.14404357,  1.45427351]]])

In [63]:
np.where(a > 0, 1, -1)

array([[[ 1,  1],
        [ 1,  1],
        [ 1, -1]],

       [[ 1, -1],
        [-1,  1],
        [ 1,  1]]])

In [64]:
np.where( a>0, a, 0)

array([[[1.76405235, 0.40015721],
        [0.97873798, 2.2408932 ],
        [1.86755799, 0.        ]],

       [[0.95008842, 0.        ],
        [0.        , 0.4105985 ],
        [0.14404357, 1.45427351]]])

In [67]:
np.random.seed(0)
a = np.random.randn(2,3,2)
a

array([[[ 1.76405235,  0.40015721],
        [ 0.97873798,  2.2408932 ],
        [ 1.86755799, -0.97727788]],

       [[ 0.95008842, -0.15135721],
        [-0.10321885,  0.4105985 ],
        [ 0.14404357,  1.45427351]]])