# 3-1 Numpy

1.3 Numpy import

In [2]:
import numpy as np

2.1 리스트를 사용하여 numpy array 만들기

In [3]:
list1 = [7, 2, 9, 10]
print(list1)
print(type(list1))

[7, 2, 9, 10]
<class 'list'>


In [5]:
array1 = np.array(list1)
print(array1)
print(type(array1))

[ 7  2  9 10]
<class 'numpy.ndarray'>


In [6]:
list2 = [[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
print(list2)
print(type(list2))

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
<class 'list'>


In [7]:
array2 = np.array(list2)
print(array2)
print(type(array2))

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
<class 'numpy.ndarray'>


list.shape

In [8]:
array1.shape

(4,)

In [9]:
array2.shape

(2, 3)

In [10]:
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [16]:
b = np.array([1,2,3,4])
print(b)
print(type(b))
print(b.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [12]:
a = np.array([[1,2,3,4]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3 4]]
<class 'numpy.ndarray'>
(1, 4)


In [14]:
print(a)
print(a.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [19]:
print(b)
print(b.T)

[1 2 3 4]
[1 2 3 4]


In [21]:
array3 = np.array([[[0,1],[2,3],[4,5]],
                  [[6,7],[8,9],[10,11]],
                  [[12,13],[14,15],[16,17]],
                  [[18,19],[20,21],[22,23]]])
print(array3)
print(array3.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)


In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a=np.arange(1,10,2)
a.shape

(5,)

# reshape

In [33]:
a = np.arange(1,11)
a.shape

(10,)

In [35]:
b=a.reshape(2,5)
b.shape
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
c=a.reshape(5,2)
print(c)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [40]:
d = c.reshape(10,)
print(d)
print(d.shape)
a==d

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# np.ravel
,np.reshape의 반대 기능 => 1차원 array로 만들어주기
order = 'C' row 우선 변경(기본값)
order = 'F' column 우선 변경

In [43]:
a = np.arange(1,11)
b = a.reshape(2,5)
print(a)
print(b)
print(np.ravel(b))
print(np.ravel(b,order='F'))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  6  2  7  3  8  4  9  5 10]


In [51]:
a = np.arange(1,13)
b = a.reshape(2,2,3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
print(np.ravel(b,order='F'))
print(np.ravel(b,order='c'))

[ 1  7  4 10  2  8  5 11  3  9  6 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 2.3 numpy에서 제공하는 함수를 사용하여 numpy array 만들기
numpy에서 제공하는 함수를 사용하여 numpy array를 만들 수 있음
이러한 기능을 제공하는 함수로는 zeros(), ones(), full(), eye() 등이 있음
zeros() : 모든 값이 0인 array 생성
ones() : 모든 값이 1인 array 생성
full() : 사용자가 지정한 특정 값을 모든 값으로 하는 array 생성
eye() : 대각선으로는 1이고 나머지는 0인 2차원 array 생성(단위 행렬이라고 함)
numpy array의 값을 모두 0으로 대체하고 싶을 때는 zeros_like() 함수를 사용함


In [56]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [57]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [59]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
x=np.array([[2,3,4],[6,5,4]])
print(x)

[[2 3 4]
 [6 5 4]]


In [64]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

# random 서브모듈 함수rand 함수를 통해 난수 생성
0,1 사이의 균일 분포에서 난수 matrix array 생성

In [66]:
np.random.rand(2,2,3)

array([[[0.96900667, 0.72869667, 0.3675486 ],
        [0.03618972, 0.30897151, 0.60621554]],

       [[0.49081148, 0.66299044, 0.19745461],
        [0.02757091, 0.02449481, 0.66299341]]])

# randn 함수
평균0, 분산1의 표준정규분포 난수 matrix array 생성

In [67]:
np.random.randn(3,3,3)

array([[[ 0.6707153 ,  0.41535567,  0.51627787],
        [-1.79516733,  1.02519978, -0.23837206],
        [-0.75035274, -1.00668576,  0.17937646]],

       [[ 1.44809222, -0.38871818, -1.26348791],
        [-0.34790158, -0.61266767,  0.03299089],
        [-0.163637  , -0.87714308, -0.50176704]],

       [[ 0.06578237,  0.27209812,  0.27242222],
        [ 0.10327171, -0.88130508, -0.38488774],
        [-0.44505891,  0.84309776,  1.93169121]]])

# seed 
랜덤한 값 동일하게 다시 생성할 때 사용

In [69]:
np.random.seed(2020)
np.random.randn(3,3,3)

array([[[-1.76884571,  0.07555227, -1.1306297 ],
        [-0.65143017, -0.89311563, -1.27410098],
        [-0.06115443,  0.06451384,  0.41011295]],

       [[-0.57288249, -0.80133362,  1.31203519],
        [ 1.27469887, -1.2143576 ,  0.31371941],
        [-1.44482142, -0.3689613 , -0.76922658]],

       [[ 0.3926161 ,  0.05729383,  2.08997884],
        [ 0.04197131, -0.04834072, -0.51315392],
        [-0.08458928, -1.21545008, -1.41293073]]])

In [71]:
np.random.randn(3,3,3) #다름

array([[[ 0.2071549 ,  1.64424216, -0.4882074 ],
        [-0.01782826,  0.46891556,  0.27987266],
        [-0.64664972, -0.54406002, -0.16008985]],

       [[ 0.03781172,  1.03383296, -1.23096117],
        [-1.24673665,  0.29572055,  2.1409624 ],
        [-0.92020227, -0.06000238,  0.27978391]],

       [[-1.53126966, -0.30293101, -0.14601413],
        [ 0.27746159, -0.13952066,  0.69515966],
        [-0.11338746, -1.233267  , -0.79614131]]])

In [72]:
np.random.seed(2020) #동일
np.random.randn(3,3,3)

array([[[-1.76884571,  0.07555227, -1.1306297 ],
        [-0.65143017, -0.89311563, -1.27410098],
        [-0.06115443,  0.06451384,  0.41011295]],

       [[-0.57288249, -0.80133362,  1.31203519],
        [ 1.27469887, -1.2143576 ,  0.31371941],
        [-1.44482142, -0.3689613 , -0.76922658]],

       [[ 0.3926161 ,  0.05729383,  2.08997884],
        [ 0.04197131, -0.04834072, -0.51315392],
        [-0.08458928, -1.21545008, -1.41293073]]])

# choice 함수
주어진 1차원 array로 부터 랜덤으로 샘플링
replace = True 복원추출(기본값)
replace = False 비복원추출

In [75]:
x=np.arange(1,50)
np.random.choice(x, size=(2,3,3), replace=False)
np.random.choice(x, size=(2,3,3), replace=True) #중복된 원소 가능

array([[[12, 42,  9],
        [26, 38,  7],
        [14, 35, 13]],

       [[42, 38, 39],
        [20, 41, 40],
        [15, 30, 13]]])

# 슬라이싱
각 차원별 범위 지정

In [83]:
x=np.arange(3,15)
y= x.reshape(3,2,2)
print(y)
y[:2,:,0]

[[[ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[3, 5],
       [7, 9]])