# 시리즈 만들기

In [14]:
import pandas as pd
import numpy as np

In [12]:
data=pd.Series([1,2,3,4,5])
data1=pd.Series({'A':[1,2,3,4,5]})
data1

A    [1, 2, 3, 4, 5]
dtype: object

# 데이터프레임 만들기

In [22]:
np.random.choice(10,10,replace=True)

array([1, 3, 1, 1, 9, 7, 8, 5, 6, 1])

In [18]:
np.random.rand(10)

array([0.39882956, 0.49432536, 0.10195845, 0.41628344, 0.27404577,
       0.34333514, 0.73968048, 0.3004    , 0.96606896, 0.55367586])

In [17]:
np.random.randn(10)

array([ 0.72282401,  1.32741733, -0.5554385 ,  0.8793541 ,  0.44556033,
        1.17045382,  1.48852072,  0.5447256 , -0.16077094,  0.88437877])

In [33]:
df=pd.DataFrame(np.random.randn(10).reshape(2,5))
df

0         1         2         3         4
0  0.045519  0.192235 -1.354170 -0.527068  0.150975
1 -0.493303  0.707105 -0.840081  0.967467 -0.896828

In [50]:
df=pd.DataFrame(data={'a':[1,2,3,4,5],
                     'b':[1,2,3,4,5],
                     'c':[1,2,3,4,5]},
                        index=['가','나','다','라','마'])
df

a  b  c
가  1  1  1
나  2  2  2
다  3  3  3
라  4  4  4
마  5  5  5

# 데이터프레임에서 시리즈 선택하기

In [52]:
type(df['a'])

pandas.core.series.Series

# index, values 사용하기

In [53]:
df.index

Index(['가', '나', '다', '라', '마'], dtype='object')

In [56]:
df.values

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]], dtype=int64)

In [55]:
df.values.T

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]], dtype=int64)

# 시리즈의 mean, min, max, std 메서드 사용하기

In [58]:
df['a'].mean()

3.0

In [59]:
df['a'].std()

1.5811388300841898

# 시리즈와 불린 추출 사용하기

In [90]:
scientists = pd.read_csv('pandas_data/scientists.csv')
scientists.head(5)

Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [76]:
scientists.dtypes

Name          object
Born          object
Died          object
Age            int64
Occupation    object
dtype: object

# 시리즈와 브로드캐스팅

In [67]:
scientists.Age*10

0    370
1    610
2    900
3    660
4    560
5    450
6    410
7    770
Name: Age, dtype: int64

# 데이터프레임과 불린 추출

In [68]:
scientists[scientists.Age>20]

Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [72]:
scientists.loc[scientists.Age>20,'Name':'Occupation']

Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

# 데이터프레임과 브로드캐스팅

In [100]:
scientists[['Age']]*100

Age
0  3700
1  6100
2  9000
3  6600
4  5600
5  4500
6  4100
7  7700

# 열의 자료형 바꾸기와 새로운 열 추가하기

In [79]:
import datetime

In [84]:
datetime.datetime.strptime(scientists.Died[0],'%Y-%m-%d')

datetime.date(1958, 4, 16)

In [91]:
scientists.Died=scientists.Died.apply(lambda x:datetime.datetime.strptime(x,'%Y-%m-%d'))
scientists.Born=scientists.Born.apply(lambda x:datetime.datetime.strptime(x,'%Y-%m-%d'))

In [ ]:
scientists.insert(4,'marriage',np.random.choice([0,1],len(scientists)))

In [95]:
scientists.marriage=scientists.marriage.astype('object')

In [96]:
scientists.dtypes

Name                  object
Born          datetime64[ns]
Died          datetime64[ns]
Age                    int64
marriage              object
Occupation            object
dtype: object

# 데이터프레임의 열 삭제하기

In [98]:
scientists.drop('marriage',axis=1,inplace=True)

In [99]:
scientists

Name       Born       Died  Age          Occupation
0     Rosaline Franklin 1920-07-25 1958-04-16   37             Chemist
1        William Gosset 1876-06-13 1937-10-16   61        Statistician
2  Florence Nightingale 1820-05-12 1910-08-13   90               Nurse
3           Marie Curie 1867-11-07 1934-07-04   66             Chemist
4         Rachel Carson 1907-05-27 1964-04-14   56           Biologist
5             John Snow 1813-03-15 1858-06-16   45           Physician
6           Alan Turing 1912-06-23 1954-06-07   41  Computer Scientist
7          Johann Gauss 1777-04-30 1855-02-23   77       Mathematician