In [1]:
import numpy as np

In [2]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])

In [3]:
names=='Bob'

array([ True, False, False,  True, False, False])

In [7]:
data=np.random.randn(6,4)

In [8]:
data

array([[ 0.32916884,  0.22582761,  1.44566291, -0.29455942],
       [ 0.17024921, -1.74564242, -0.63378466, -0.13695591],
       [-0.48935098,  0.44437822, -1.14849399, -1.50909821],
       [-0.15880924, -1.89831517, -1.35520621,  1.53656117],
       [ 1.27076506,  0.40978375, -0.31158587,  0.19641909],
       [-1.37868787, -0.38763667,  0.79719607,  0.53799408]])

In [9]:
data[names=='Bob']

array([[ 0.32916884,  0.22582761,  1.44566291, -0.29455942],
       [-0.15880924, -1.89831517, -1.35520621,  1.53656117]])

In [10]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [12]:
names=='Bob'

array([ True, False, False,  True, False, False])

In [13]:
data

array([[ 0.32916884,  0.22582761,  1.44566291, -0.29455942],
       [ 0.17024921, -1.74564242, -0.63378466, -0.13695591],
       [-0.48935098,  0.44437822, -1.14849399, -1.50909821],
       [-0.15880924, -1.89831517, -1.35520621,  1.53656117],
       [ 1.27076506,  0.40978375, -0.31158587,  0.19641909],
       [-1.37868787, -0.38763667,  0.79719607,  0.53799408]])

In [16]:
data[names=='Bob', 2:]
data[names=='Bob', 3]

array([-0.29455942,  1.53656117])

In [21]:
names!='Bob' #names에 저장된 각각의 자료와 'Bob'을 비교했을때 같지 않나?
data[names!='Bob']
~(names=='Bob') # ~(비교연산결과) => 비교 연산 결과의 반대

array([False,  True,  True, False,  True,  True])

In [22]:
data[~(names=='Bob') ]

array([[ 0.17024921, -1.74564242, -0.63378466, -0.13695591],
       [-0.48935098,  0.44437822, -1.14849399, -1.50909821],
       [ 1.27076506,  0.40978375, -0.31158587,  0.19641909],
       [-1.37868787, -0.38763667,  0.79719607,  0.53799408]])

In [25]:
cond=names=='Bob'
cond

array([ True, False, False,  True, False, False])

In [27]:
~cond
data[~cond]

array([[ 0.17024921, -1.74564242, -0.63378466, -0.13695591],
       [-0.48935098,  0.44437822, -1.14849399, -1.50909821],
       [ 1.27076506,  0.40978375, -0.31158587,  0.19641909],
       [-1.37868787, -0.38763667,  0.79719607,  0.53799408]])

In [32]:
mask= (names=='Bob') | (names=='Will') #| : or
data[mask] #이름이 밥이거나 윌인 사람의 data를 추출

array([[ 0.32916884,  0.22582761,  1.44566291, -0.29455942],
       [-0.48935098,  0.44437822, -1.14849399, -1.50909821],
       [-0.15880924, -1.89831517, -1.35520621,  1.53656117],
       [-1.37868787, -0.38763667,  0.79719607,  0.53799408]])

In [33]:
data

array([[ 0.32916884,  0.22582761,  1.44566291, -0.29455942],
       [ 0.17024921, -1.74564242, -0.63378466, -0.13695591],
       [-0.48935098,  0.44437822, -1.14849399, -1.50909821],
       [-0.15880924, -1.89831517, -1.35520621,  1.53656117],
       [ 1.27076506,  0.40978375, -0.31158587,  0.19641909],
       [-1.37868787, -0.38763667,  0.79719607,  0.53799408]])

In [34]:
data<0

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [35]:
data[data<0]

array([-0.29455942, -1.74564242, -0.63378466, -0.13695591, -0.48935098,
       -1.14849399, -1.50909821, -0.15880924, -1.89831517, -1.35520621,
       -0.31158587, -1.37868787, -0.38763667])

In [36]:
data[data<0]=0

In [37]:
data

array([[0.32916884, 0.22582761, 1.44566291, 0.        ],
       [0.17024921, 0.        , 0.        , 0.        ],
       [0.        , 0.44437822, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.53656117],
       [1.27076506, 0.40978375, 0.        , 0.19641909],
       [0.        , 0.        , 0.79719607, 0.53799408]])

In [40]:
# names에서 이름이 Will이 아닌 사람들에 대한 index를 추출하여(0,1,3,4)
# data 배열의 해당 index 자료 값을 모두 10으로 변경하시오.
names
data

array([[0.32916884, 0.22582761, 1.44566291, 0.        ],
       [0.17024921, 0.        , 0.        , 0.        ],
       [0.        , 0.44437822, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.53656117],
       [1.27076506, 0.40978375, 0.        , 0.19641909],
       [0.        , 0.        , 0.79719607, 0.53799408]])

In [43]:
data[names!='Will']=10
data

array([[10.        , 10.        , 10.        , 10.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [ 0.        ,  0.44437822,  0.        ,  0.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [ 0.        ,  0.        ,  0.79719607,  0.53799408]])

In [45]:
arr=np.zeros((8,4))

In [53]:
for i in range(8):
    arr[i]=i+10
#arr[0]=10

In [54]:
arr

array([[10., 10., 10., 10.],
       [11., 11., 11., 11.],
       [12., 12., 12., 12.],
       [13., 13., 13., 13.],
       [14., 14., 14., 14.],
       [15., 15., 15., 15.],
       [16., 16., 16., 16.],
       [17., 17., 17., 17.]])

In [58]:
arr[4]
arr[4].shape
arr[[4]]
arr[[4]].shape

(1, 4)

In [62]:
arr[4,3]#4행3열 요소값 출력
arr[[4,3]] #4행, 3행 출력
arr[[4,3,0,6]] #4행, 3행, 0행, 6행 출력

array([[14., 14., 14., 14.],
       [13., 13., 13., 13.],
       [10., 10., 10., 10.],
       [16., 16., 16., 16.]])

In [64]:
arr[[-3,-5]] #뒤에서 부터 3번째, 5번째 행

array([[15., 15., 15., 15.],
       [13., 13., 13., 13.]])

In [66]:
#8행 4열 array생성, 데이터는 10~41까지 저장
arr=np.arange(10,42).reshape(8,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [67]:
#arr에서 1, 5, 7, 2 행 추출
arr[[1,5,7,2]]

array([[14, 15, 16, 17],
       [30, 31, 32, 33],
       [38, 39, 40, 41],
       [18, 19, 20, 21]])

In [70]:
arr[[1,5,7,2], [0,3,1,2]]

array([14, 33, 39, 20])

In [72]:
arr[[1,5,7,2]] [:,[0,3,1,2]]

array([[14, 17, 15, 16],
       [30, 33, 31, 32],
       [38, 41, 39, 40],
       [18, 21, 19, 20]])

In [75]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.T.shape

(5, 3)

In [79]:
#arr.T.T
arr.shape

(3, 5)

In [80]:
np.dot(arr,arr.T) #행렬 곱셈 3행5열 * 5행3열 => 3행 3열
#arr.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [83]:
arr=np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [86]:
x=np.random.randn(8)
y=np.random.randn(8)

In [87]:
x

array([ 1.28886585,  0.79600888, -0.92851788,  0.45954001,  1.9440133 ,
        0.01288543,  0.24834268,  0.73499074])

In [88]:
y

array([-0.74681198,  0.32765628, -1.26758353,  1.00552459,  0.85998508,
       -0.36947382,  1.11766302,  0.45149641])

In [90]:
np.maximum(x,y) #각 배열의 두 원소 중 큰 값을 리턴
np.minimum(x,y) 

array([-0.74681198,  0.32765628, -1.26758353,  0.45954001,  0.85998508,
       -0.36947382,  0.24834268,  0.45149641])

In [91]:
arr=np.random.randn(7)*5
arr

array([-6.35509784, -8.25248533, -6.33010363, -1.06747915, -0.34615815,
       -0.47242645, -4.52770888])

In [92]:
np.modf(arr)
#(array(), array())  튜플

(array([-0.35509784, -0.25248533, -0.33010363, -0.06747915, -0.34615815,
        -0.47242645, -0.52770888]),
 array([-6., -8., -6., -1., -0., -0., -4.]))

In [95]:
remainder, whole_part=np.modf(arr)

In [96]:
remainder

array([-0.35509784, -0.25248533, -0.33010363, -0.06747915, -0.34615815,
       -0.47242645, -0.52770888])

In [97]:
whole_part

array([-6., -8., -6., -1., -0., -0., -4.])

In [105]:
points=np.arange(-5, 5, 0.01)
points.shape # -5, -4.99, ...,0, ..., 4.99

(1000,)

In [100]:
xs,ys=np.meshgrid(points,points)
# 두 개의 1차원 배열을 입력받아서 가능한 모든 (x,y) 짝을 만들 수 있는
# 2차원 배열 2개를 리턴

In [106]:
xs.shape
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [107]:
ys.shape
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [108]:
z=np.sqrt(xs**2+ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [ ]:
x,y
x는0~2
y는0~4 
사각형 영역 생성
(x,y)=(0,0), (0,1), (0,2), (0,3), (0,4), ... (2,4) #그리드포인트

In [109]:
x=np.arange(3)
x

array([0, 1, 2])

In [110]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [112]:
xx, yy=np.meshgrid(x,y)

In [113]:
xx

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [114]:
yy

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [117]:
[list(zip(x,y)) for x,y in zip(xx,yy)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [118]:
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [119]:
cond=np.array([True, False, True, True, False])

In [125]:
res=[(x if c else y )for x,y,c in zip(xarr,yarr,cond)]
res

[1.1, 2.2, 1.3, 1.4, 2.5]

In [124]:
# (x if c else y ) for x,y,c in zip(xarr,yarr,cond)
# #만약 c값이 참이면 x를 거짓이면 y를 취해라

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, True),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

In [126]:
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [127]:
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [128]:
cond

array([ True, False,  True,  True, False])

In [129]:
np.where(cond, xarr, yarr) #cond(조건)가 참이면 xarr, 거짓이면 yarr 취함

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [130]:
# 4행 4열의 행렬을 randn함수를 수행한 값으로 초기화하여 정의
# 행렬의 요소값 중에서 1보다 크면 1을 출력, 작으면 0을 출력
arr=np.random.randn(4,4)
arr

array([[ 1.09702858,  0.26860647,  1.23884584,  1.78898608],
       [-0.44166262, -0.84594366, -0.67249341,  0.18864629],
       [ 0.94599243,  1.99047567, -0.6605812 ,  0.61102189],
       [-0.22062631, -1.82003109,  0.77180439,  1.78301518]])

In [131]:
arr>1

array([[ True, False,  True,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [132]:
np.where(arr>1, 1, 0)

array([[1, 0, 1, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [133]:
# 4행 4열의 행렬을 randn함수를 수행한 값으로 초기화하여 정의
# 행렬의 요소값 중에서 1보다 크면 1을 출력, 작으면 원래 값을 그대로 출력
np.where(arr>1, 1, arr)

array([[ 1.        ,  0.26860647,  1.        ,  1.        ],
       [-0.44166262, -0.84594366, -0.67249341,  0.18864629],
       [ 0.94599243,  1.        , -0.6605812 ,  0.61102189],
       [-0.22062631, -1.82003109,  0.77180439,  1.        ]])

In [134]:
arr=np.random.randn(5,4)
arr

array([[-1.04692374, -0.09658382, -2.21613175,  0.05172894],
       [ 0.71752859,  0.77932806,  0.6816619 ,  0.40128687],
       [ 0.30491843,  0.90237202,  0.12927471,  0.41959013],
       [ 0.88113911,  0.11703013, -0.26000279, -0.57977592],
       [ 0.95364837, -0.2382361 , -0.85818496, -1.52994324]])

In [137]:
arr.mean() #np.mean(arr)

-0.024313752407509916

In [138]:
arr.sum()

-0.4862750481501983

In [141]:
arr

array([[-1.04692374, -0.09658382, -2.21613175,  0.05172894],
       [ 0.71752859,  0.77932806,  0.6816619 ,  0.40128687],
       [ 0.30491843,  0.90237202,  0.12927471,  0.41959013],
       [ 0.88113911,  0.11703013, -0.26000279, -0.57977592],
       [ 0.95364837, -0.2382361 , -0.85818496, -1.52994324]])

In [142]:
arr.mean(axis=1)
arr.sum(axis=1) #열 방향으로 이동해가면서 요소값의 합

array([-3.30791037,  2.57980542,  1.7561553 ,  0.15839053, -1.67271592])

In [143]:
arr.mean(axis=0)
arr.sum(axis=0)#행 방향으로 이동해가면서 요소값의 합

array([ 1.81031077,  1.46391029, -2.52338289, -1.23711322])

In [147]:
arr=np.arange(1,8)
arr.cumsum() #누적합

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [148]:
arr.cumprod() # 7!=5040

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

In [150]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
print(arr.cumsum())
print("="*50)
print(arr.cumsum(axis=0)) #행 방향으로 이동(위->아래)
print(arr.cumprod(axis=0)) #행 방향으로 이동(위->아래)
print("="*50)
print(arr.cumsum(axis=1)) #열 방향으로 이동(좌->우)
print(arr.cumprod(axis=1)) #열 방향으로 이동(위->아래)

[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


In [158]:
arr=np.random.randn(100)
arr
arr.mean()
arr.std()

1.015192318220708

In [167]:
arr
#arr에서 양수의 합
#arr최대값/최소값
(arr>0).sum() #양수의 개수
arr[arr>0].sum() #양수의 합
arr.max()
arr.min()

-2.7781950740852155

In [171]:
arr
#양수는 모두 1로 음수는 모두 -1로 치환하시오
arr=np.where(arr>0, 1, -1)
arr

array([-1, -1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
       -1, -1,  1,  1,  1, -1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1, -1,
       -1,  1,  1, -1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1, -1, -1, -1,
        1,  1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1,
       -1,  1, -1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1])

In [177]:
bools=np.array([False, False, True, False])

In [178]:
bools.any() #어느 하나라도 True가 있으면 True가 출력

True

In [179]:
bools.all()#모든 값이 True가 있으면 True가 출력

False

In [180]:
arr=np.random.randn(6)
arr

array([1.47078581, 0.92048364, 0.10286743, 0.2619422 , 0.07694833,
       1.40338305])

In [181]:
arr.sort()

In [182]:
arr

array([0.07694833, 0.10286743, 0.2619422 , 0.92048364, 1.40338305,
       1.47078581])

In [186]:
arr=np.random.randn(5,3)
arr

array([[ 0.83563648, -0.30610657,  1.74295125],
       [ 0.7581476 ,  1.81037507,  1.10776381],
       [ 0.19611313,  0.89748471, -0.29060752],
       [-1.47625848, -0.90264529, -1.26961192],
       [-0.4905145 , -0.67670135, -0.56846346]])

In [187]:
#arr.sort() #오름차순 정렬(열 방향, axis=1 디폴트)
arr.sort(axis=0) #오름차순 정렬(행 방향)

In [188]:
arr

array([[-1.47625848, -0.90264529, -1.26961192],
       [-0.4905145 , -0.67670135, -0.56846346],
       [ 0.19611313, -0.30610657, -0.29060752],
       [ 0.7581476 ,  0.89748471,  1.10776381],
       [ 0.83563648,  1.81037507,  1.74295125]])

In [189]:
arr=np.array([4,1,7,5,9])

In [190]:
np.sort(arr)
arr.sort()

In [191]:
arr

array([1, 4, 5, 7, 9])

In [194]:
arr[::-1] #넘파이는 별도로 내림차순 정렬이 없음. 오름차순 정렬 결과를 뒤에서부터 참조

array([9, 7, 5, 4, 1])

In [195]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])

In [196]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [198]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [199]:
arr=np.array([6,0,0,3,2,5])

In [200]:
np.in1d(arr, [2,3,6]) #arr의 각 원소가 [2,3,6]의 원소에 포함되어 있는지 여부 출력

array([ True, False, False,  True,  True, False])

In [201]:
a=np.array([1,2,3])
b=np.array([10,20,30])

In [205]:
2*a+b
(a==2)&(b>10)

array([False,  True, False])

In [213]:
a=np.arange(6).reshape(2,3)
len(a) #행의 개수
len(a[0]) #열의 개수
np.shape(a)
np.shape(a)[0] #행의 개수
np.shape(a)[1]#열의 개수

3

In [220]:
# 리스트:1차원
# 리스트의리스트:2차원
# 리스트의리스트의리스트:3차원 배열
#2*3*4
d=np.arange(10,34).reshape(2,3,4)
d

array([[[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]],

       [[22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]]])

In [229]:
len(d) #2, 가장 바깥쪽 대괄호 안에 요소가 2개 있음
len(d[0]) #3, 바깥쪽 대괄호 안에 요소가 3개 있음
len(d[0][0]) #4, 가장 안쪽 요소의 개수
#d[1]
np.shape(d)[0] #[1], [2]

2

In [230]:
d.ndim


3

In [233]:
a=np.arange(6).reshape(2,3)

In [240]:
#마지막 행의 마지막열 출력
a[1][2]
a
a[-1][2]
a[-1][-1]

5

In [242]:
x=np.array([1, 2.0])
x.dtype

dtype('float64')

In [244]:
x=np.array([1,2], dtype="f")
x.dtype

dtype('float32')

In [245]:
x

array([1., 2.], dtype=float32)

In [249]:
np.inf #무한대
np.nan  #정의할 수 없는 숫자

nan

In [250]:
a=np.array([0,1,-1,0])
b=np.array([1,0,0,0])

In [251]:
a/b

<ipython-input-251-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b
<ipython-input-251-aae42d317509>:1: RuntimeWarning: invalid value encountered in true_divide
  a/b


array([  0.,  inf, -inf,  nan])

In [252]:
np.log(0)

<ipython-input-252-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [253]:
np.linspace(0,100,5) #0~100까지 5개의 수를 구간으로 나누어 출력

array([  0.,  25.,  50.,  75., 100.])

In [256]:
a=np.arange(12)
a.reshape(3,4)
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [259]:
a
#2*2*3 3차원배열
a.reshape(2,2,-1)
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [269]:
a=np.arange(12)
a.shape

(12,)

In [274]:
a
a=a.reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [281]:
#다차원 -> 1차원
#a.reshape(12,)
#a.flatten()
#a.ravel()
np.arange(5).shape

(5,)

In [283]:
x=np.arange(5).reshape(1,5)
x.shape

(1, 5)

In [284]:
x=np.arange(5).shape
x

(5,)

In [287]:
x=np.arange(5)
x #(5,)

array([0, 1, 2, 3, 4])

In [289]:
print(x[:, np.newaxis])
print(x[:, np.newaxis].shape)
#1차원 증가 : np.newaxis => (5,) -> (5,1)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [293]:
#행의 수가 같은 배열을 옆으로 연결(열이 증가)
a=np.ones((2,3))
b=np.zeros((2,2))

In [294]:
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [296]:
np.hstack([a,b])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [299]:
b=np.zeros((2,3))
np.vstack([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [300]:
a=np.arange(6).reshape(2,3)

In [301]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [302]:
#tile:동일한 배열 반복하여 연결
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [308]:
np.tile(a,(3,2)) #위->아래 방향으로 3번, 좌->우 방향으로 2번 반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [311]:
x=np.arange(5,14).reshape(3,3)
x

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [316]:
#기술통계
len(x)
np.mean(x)
np.var(x) #분산
np.std(x) #표준편차
np.median(x) #중위수

9.0

In [318]:
np.percentile(x,0) #최소값
np.percentile(x,25) #1, 1사분위수는 25% 백분위수와 같다
np.percentile(x,50) #2,
np.percentile(x,75) #3
np.percentile(x,100) #4

13.0

In [319]:
np.random.seed(111)

In [320]:
np.random.rand(5) #0이상 1미만 난수

array([0.61217018, 0.16906975, 0.43605902, 0.76926247, 0.2953253 ])

In [321]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [322]:
np.random.shuffle(x)

In [323]:
x

array([6, 5, 3, 0, 9, 2, 4, 1, 7, 8])

In [325]:
#데이터 샘플링 함수 프로토타입
#np.random.choice(배열, 크기, replace=True, 확률)

In [326]:
arr1=np.arange(11,20)

In [328]:
np.random.choice(arr1, 5) #기본값으로 복원추출

array([17, 16, 19, 17, 13])

In [329]:
np.random.choice(arr1, 5, replace=True)

array([17, 15, 14, 18, 14])

In [331]:
np.random.choice(10, 5) #10은 np.arange(10)을 의미함

array([1, 1, 7, 8, 7])

In [332]:
np.random.choice(5, 5)

array([1, 4, 3, 0, 3])

In [338]:
np.random.choice(5, 5, p=[0.1, 0.2, 0, 0.5, 0.2]) #확률

array([3, 1, 3, 3, 1])

In [348]:
np.random.randint(10)  #0~9
np.random.randint(5,10) #(low,high) 5~9
np.random.randint(5,10,3) #3개 추출
np.random.randint(5,10,size=5) #5개 추출

array([6, 5, 7, 6, 9])

In [349]:
np.unique([1,1,3,3,5])

array([1, 3, 5])

In [355]:
# x=np.unique([1,1,3,3,5], return_counts=True)
# x
idx, cnt =np.unique([1,1,3,3,5], return_counts=True)

In [357]:
#x[1]
idx[1]
cnt[1]

array([2, 2, 1], dtype=int64)

In [358]:
#주사위를 5번 던져서 나온 수 집합 = [1,1,3,3,5]
#2 0 2 0 1 0

In [361]:
d=np.bincount([1,1,3,3,5], minlength=7)# minlength=7이므로 0~6까지 카운트 범위
#bincount는 0부터 센다

In [364]:
d
d=d[1:]

In [365]:
d

array([2, 0, 2, 0, 1, 0], dtype=int64)

In [366]:
#퀴즈
#넘파이 난수 생성 -> 로또 생성(1~45)

In [367]:
from sklearn.datasets import load_iris 

In [368]:
iris = load_iris()

In [372]:
#iris.data
iris.data[0,:] #첫번째 꽃 데이터

#첫번째 꽃 데이터와 가장 유사한 꽃 데이터 & 유클리디안를 출력
#유클리디안 거리 기반

array([5.1, 3.5, 1.4, 0.2])

### hw2

In [7]:
# 1. 파이썬 연습문제
# - 입력 받은 정수가 음수인지 양수인지 0인지 알려주세요
def ispos():
    try:
        a=int(input('정수를 입력하세요.'))
        if a >0:
            print('양수입니다.')
        elif a<0:
            print('음수입니다.')
        else:
            print('0입니다')
    except:
        err='정수를 입력하세요.'
        print(err)
# ispos()


# - 'hello'를 지정한 횟수(0 <= n <= 3)만큼 출력해 보세요.
print('hello'*3)

# - 0~9사이의 정수를 거꾸로 출력해 보세요.
print(list(range(10))[::-1])

hellohellohello
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


NameError: name 'random' is not defined

In [13]:
# - 임의의 리스트를 생성한 후, 리스트를 거꾸로 출력하는 반복문을 만들어 보세요.
# - 리스트를 출력하면서 앞에 일련번호를 붙여주세요. 
# # 0 2
# # 1 4
# # 2 6
import random

random.seed(2021)
r_list=random.sample(range(100),20)

for i in range(len(r_list)):
    print(i,r_list[::-1][i])

0 13
1 95
2 6
3 21
4 20
5 9
6 37
7 34
8 40
9 8
10 73
11 60
12 56
13 4
14 81
15 31
16 35
17 69
18 80
19 51


In [21]:
# # - 리스트에서 중복 값을 제거해 보세요.
import numpy as np
ns = [1, 3, 5, 1, 3, 5, 1, 3, 5]
np_ns=np.array(ns)

print(np.unique(np_ns))
print(np.unique(np_ns,return_counts=True))
print(set(ns))

np.bincount(np_ns)

[1 3 5]
(array([1, 3, 5]), array([3, 3, 3], dtype=int64))
{1, 3, 5}


array([0, 3, 0, 3, 0, 3], dtype=int64)

In [35]:
# 2. numpy 연습문제
# 1)랜덤하게 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고
# 이 데이터에 대해 다음과 같은 값을 구한다.
data=np.random.randn(30).reshape(5,6)
print(data)
# -전체의 최댓값
print(max([max(i) for i in data]))

# -각 행의 합
print([sum(i) for i in data])

# -각 행의 최댓값
print([max(i) for i in data])


# -각 열의 평균
print([sum(i)/len(i) for i in np.transpose(data)])

# -각 열의 최솟값
print([min(i) for i in np.transpose(data)])


[[ 0.47649537 -0.95751172 -0.0980988  -0.00607085  0.53473262 -0.79244704]
 [-0.78167125  0.25655984  2.52123687 -0.70420589 -0.05320912 -1.19692463]
 [-0.03654307 -2.20534268 -0.59978393  0.2885224   0.17318071  0.79057352]
 [ 0.39037428 -0.78245727  0.76632875  0.34011413  0.98323034 -1.31487313]
 [-0.45581509 -0.49499563 -0.5150825   0.64041269  0.93978292  0.71882182]]
2.521236872825203
[-0.842900425541833, 0.04178582504384387, -1.58939304821453, 0.3827170870946781, 0.8331242062025965]
[0.534732616604387, 2.521236872825203, 0.7905735218222213, 0.9832303420309594, 0.9397829150996809]
[-0.0814319523361647, -0.8367494929056785, 0.4149200793733493, 0.11175449525054726, 0.5155434923931721, -0.3589698928582745]
[-0.7816712486201601, -2.2053426837758954, -0.5997839289019852, -0.7042058908107832, -0.05320911857132268, -1.3148731341920992]


In [43]:
# 2)다음 행렬과 같은 행렬이 있다.
# m = np.array([[ 0,  1,  2,  3,  4],
#             [ 5,  6,  7,  8,  9],
#             [10, 11, 12, 13, 14]])
# -이 행렬에서 값 7 을 인덱싱한다.
# -이 행렬에서 값 14 을 인덱싱한다.
# -이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# -이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# -이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
print(m[1][2],m[2,4],m[1,1:3],m[1:3,2],m[:2,3:])

7 14 [6 7] [ 7 12] [[3 4]
 [8 9]]


In [67]:
# 3) 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.
# (코드를 효율적으로)
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])
base=np.zeros(60).reshape(12,5)
print(base)
temp1=(np.arange(1,16)*10).reshape(3,5)
print(temp1)
base[3:6]=temp1
base[9:12]=temp1
base[:,3:][base[:,3:]==0]=1
base

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [70]:
# 4) 다음 행렬과 같은 배열이 있다.
# x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
#              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# -이 배열에서 3의 배수를 찾아라.
# -이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# -이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0)&(x%4==1)])



[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [77]:
# 5) 
# -동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
# -주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
ans=[]
random.seed(2021)
for i in range(100):
    ans.append(np.random.choice([0,1],1,p=[0.5,0.5])[0])
sum(ans)/len(ans)

0.49

In [90]:
# 6)다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 
# 영어 성적을 기준으로 각 열(column)을 재정렬하라.
# array([[  1,    2,    3,    4],
#        [ 46,   99,  100,   71],
#        [ 81,   59,   90,  100]])
test=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]]).transpose()
np.array(sorted(test, key=lambda x:x[1])).transpose()

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [96]:
# 3. iris data 유사 데이터 추출
 # 사이킷런 패키지 임포트
from sklearn.datasets import load_iris 
iris = load_iris()  # 데이터 로드
  # 첫 번째 꽃의 데이터
iris.data[0, :]

ans=[]
for i in range(len(iris.data)):
    a=(iris.data-iris.data[i, :])**2
    b=np.sqrt(np.apply_along_axis(sum,1,a))
    b[i]=b.max()
    ans.append([i,np.where(b.min()==b)[0][0]])

ans

array([5.1, 3.5, 1.4, 0.2])